### PR TITLE
Fix no response if TTN credentials are not valid.

### PR DESCRIPTION
**Pull request by abrahamSecmotic**
Fix this issue: https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/issues/68

And fix the loop to the MQTT connection

### CODE REVIEW

**Comment by cpezuela** [comment]
Thanks!!

**Review by cpezuela — COMMENTED** [review]
ok

**Comment by JoseSecmotic** [comment]
Hi,

Why has this been closed without merging? I was following up this pull request because we consider it very important for the correct behavior of the GE

**Comment by sirnino** [comment]
Me and my team were waiting for it as well. Why closed without merging?

**Pull request closed without merging**
