### PR TITLE
Fix #58 - Add Docker Secrets

### LINKED ISSUE #58: Docker releases?
Hi! 
I noticed the [official docker image](https://hub.docker.com/r/fiware/iotagent-lorawan/) linked in the README is 6 months old now. Two questions: 
- Do you plan to add automated docker builds?
- Is there a versioning schema for the this Agent? (to know if I should update and to which version, etc.)

Thanks in advance!

### PR DESCRIPTION
**Pull request by jason-fox**
Port over Docker Secrets support
see:  https://github.com/telefonicaid/iotagent-json/pull/390

### CODE REVIEW

**Comment by dcalvoalonso** [comment]
@jason-fox Is this ready to be reviewed and merges? I see that the corresponding / twin PR in the JSON IoT Agent has been merged: https://github.com/telefonicaid/iotagent-json/pull/390 :)

**Comment by jason-fox** [comment]
@dcalvoalonso - yes it should be, but don't just accept my word for it, please review test - the `Dockerfile` and `entrypoint.sh` are slightly different for each IoT Agent. I assume I haven't broken anything, but a second pair of eyes is very welcome.

**Comment by dcalvoalonso** [comment]
Sure, I will review it before merging and ask any doubt or comment! :)

**Comment by dcalvoalonso** [comment]
@jason-fox I have reviewed the changes and run some integration tests with the resulting Docker images and everything seems to be OK. :)

Thanks for the contribution!

LGTM

**Pull request merged**
